name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v5
    - name: Use Node.js 22.x
      uses: actions/setup-node@v5
      with:
        node-version: 22.x
        cache: 'npm'
    - run: npm ci
    - run: npm run lint
    - run: npm run test:ci
    - run: npm run build